# Generated by Django 5.2.3 on 2025-06-26 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('quantidade_movimentada', models.PositiveIntegerField(verbose_name='Quantidade Movimentada')),
                ('data_hora_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Motivo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.itemestoque', verbose_name='Item')),
                ('movimentado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Movimentado Por')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_hora_movimentacao'],
            },
        ),
    ]
