# Generated by Django 5.2.3 on 2025-06-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_movimentacaoestoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemestoque',
            options={'ordering': ['nome'], 'verbose_name': 'Item de Estoque', 'verbose_name_plural': 'Itens de Estoque'},
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=5, verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='nome',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome do Item'),
        ),
    ]
