# Generated by Django 5.2.3 on 2025-07-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Cargo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Líder')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Líder',
                'verbose_name_plural': 'Líderes',
            },
        ),
        migrations.CreateModel(
            name='TipoAbsenteismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, unique=True, verbose_name='Descrição do Tipo')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('e_ausencia', models.BooleanField(default=True, verbose_name='Conta como Ausência?')),
            ],
            options={
                'verbose_name': 'Tipo de Absenteísmo',
                'verbose_name_plural': 'Tipos de Absenteísmo',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Contrato')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
            },
        ),
        migrations.CreateModel(
            name='RegistroAbsenteismoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('atestado_medico', models.BooleanField(default=False, verbose_name='Atestado Médico?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_absenteismo_diario', to='epi.colaboradorepi', verbose_name='Colaborador')),
                ('tipo_absenteismo', models.ForeignKey(default=16, on_delete=django.db.models.deletion.PROTECT, to='rh.tipoabsenteismo', verbose_name='Tipo de Absenteísmo')),
            ],
            options={
                'verbose_name': 'Registro de Absenteísmo Diário',
                'verbose_name_plural': 'Registros de Absenteísmo Diários',
                'ordering': ['-data_inicio', 'colaborador__nome_completo'],
                'constraints': [models.UniqueConstraint(fields=('colaborador', 'data_inicio', 'data_fim', 'tipo_absenteismo'), name='unique_registro_absenteismo_for_period')],
            },
        ),
    ]
