# Generated by Django 5.2.3 on 2025-07-22 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0002_initial'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do Treinamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Treinamento')),
                ('carga_horaria', models.PositiveIntegerField(blank=True, help_text='Duração total do treinamento em horas.', null=True, verbose_name='Carga Horária (horas)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Treinamento Ativo')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nome'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='lider',
            options={'ordering': ['nome'], 'verbose_name': 'Líder', 'verbose_name_plural': 'Líderes'},
        ),
        migrations.AlterModelOptions(
            name='tipocontrato',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Contrato', 'verbose_name_plural': 'Tipos de Contrato'},
        ),
        migrations.CreateModel(
            name='ParticipacaoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('C', 'Concluído'), ('N', 'Não Concluído'), ('X', 'Cancelado')], default='P', max_length=1, verbose_name='Status da Participação')),
                ('data_registro_participacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro da Participação')),
                ('nota_avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nota da Avaliação')),
                ('certificado_emitido', models.BooleanField(default=False, verbose_name='Certificado Emitido')),
                ('data_emissao_certificado', models.DateField(blank=True, null=True, verbose_name='Data de Emissão do Certificado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações da Participação')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_treinamento', to='epi.colaboradorepi', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Participação em Turma',
                'verbose_name_plural': 'Participações em Turmas',
                'ordering': ['turma__data_realizacao', 'colaborador__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='TurmaTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateField(verbose_name='Data de Realização')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horário de Fim')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local do Treinamento')),
                ('instrutor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Instrutor')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações da Turma')),
                ('participantes', models.ManyToManyField(related_name='turmas_participadas', through='rh.ParticipacaoTurma', to='epi.colaboradorepi', verbose_name='Participantes da Turma')),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='rh.treinamento', verbose_name='Treinamento')),
            ],
            options={
                'verbose_name': 'Turma de Treinamento',
                'verbose_name_plural': 'Turmas de Treinamento',
                'ordering': ['-data_realizacao', 'treinamento__nome'],
                'unique_together': {('treinamento', 'data_realizacao', 'local')},
            },
        ),
        migrations.AddField(
            model_name='participacaoturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='rh.turmatreinamento', verbose_name='Turma de Treinamento'),
        ),
        migrations.AlterUniqueTogether(
            name='participacaoturma',
            unique_together={('colaborador', 'turma')},
        ),
    ]
