# Generated by Django 5.2.3 on 2025-06-26 18:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('cpf', models.CharField(help_text='Formato: XXX.XXX.XXX-XX', max_length=14, unique=True, verbose_name='CPF')),
                ('data_admissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Admissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do EPI')),
                ('ca', models.CharField(help_text='Certificado de Aprovação (obrigatório)', max_length=20, unique=True, verbose_name='CA (Certificado de Aprovação)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('validade_ca', models.DateField(blank=True, help_text='Data de vencimento do Certificado de Aprovação', null=True, verbose_name='Validade do CA')),
                ('fabricante', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('estoque_minimo', models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de EPI')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de EPI',
                'verbose_name_plural': 'Tipos de EPI',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EntradaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_epi', to='epi.epi', verbose_name='EPI')),
            ],
            options={
                'verbose_name': 'Entrada de EPI',
                'verbose_name_plural': 'Entradas de EPI',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='SaidaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Entregue')),
                ('data_saida', models.DateTimeField(auto_now_add=True, verbose_name='Data de Saída')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações da Entrega')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_recebidos', to='epi.colaborador', verbose_name='Colaborador')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas_epi', to='epi.epi', verbose_name='EPI')),
            ],
            options={
                'verbose_name': 'Saída de EPI',
                'verbose_name_plural': 'Saídas de EPI',
                'ordering': ['-data_saida'],
            },
        ),
        migrations.AddField(
            model_name='epi',
            name='tipo_epi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epis', to='epi.tipoepi', verbose_name='Tipo de EPI'),
        ),
    ]
