# Generated by Django 5.2.3 on 2025-06-26 19:05

import django.db.models.deletion
import django.utils.timezone
import epi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaepi',
            name='assinatura_digital',
            field=models.ImageField(blank=True, null=True, upload_to=epi.models.signature_upload_to, verbose_name='Assinatura Digital'),
        ),
        migrations.AlterField(
            model_name='saidaepi',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epis_recebidos', to='epi.colaborador', verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='saidaepi',
            name='data_saida',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora da Saída'),
        ),
        migrations.AlterField(
            model_name='saidaepi',
            name='epi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas_epi', to='epi.epi', verbose_name='EPI'),
        ),
    ]
