# Generated by Django 5.2.3 on 2025-07-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epi', '0001_initial'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorepi',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='colaboradorepi',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.lider', verbose_name='Líder'),
        ),
        migrations.AddField(
            model_name='colaboradorepi',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.tipocontrato', verbose_name='Tipo de Contrato'),
        ),
        migrations.AddField(
            model_name='entradaepi',
            name='epi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_epi', to='epi.epi', verbose_name='EPI'),
        ),
        migrations.AddField(
            model_name='saidaepi',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epis_recebidos', to='epi.colaboradorepi', verbose_name='Colaborador'),
        ),
        migrations.AddField(
            model_name='saidaepi',
            name='epi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas_epi', to='epi.epi', verbose_name='EPI'),
        ),
        migrations.AddField(
            model_name='epi',
            name='tipo_epi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epis', to='epi.tipoepi', verbose_name='Tipo de EPI'),
        ),
    ]
