# Generated by Django 5.2.3 on 2025-06-26 19:32

import epi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0002_saidaepi_assinatura_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaepi',
            name='pdf_documento',
            field=models.FileField(blank=True, null=True, upload_to=epi.models.pdf_upload_to, verbose_name='Documento PDF da Saída'),
        ),
    ]
