# Generated by Django 5.2.3 on 2025-06-26 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Patrimônio',
                'verbose_name_plural': 'Categorias de Patrimônio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocalizacaoPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Localização')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Localização')),
            ],
            options={
                'verbose_name': 'Localização de Patrimônio',
                'verbose_name_plural': 'Localizações de Patrimônio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Bem Patrimonial')),
                ('codigo_patrimonial', models.CharField(max_length=100, unique=True, verbose_name='Código Patrimonial')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série (Opcional)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Aquisição (R$)')),
                ('estado_conservacao', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('SUCATA', 'Sucata')], default='BOM', max_length=20, verbose_name='Estado de Conservação')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro no Sistema')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_patrimonio', to='patrimonio.categoriapatrimonio', verbose_name='Categoria')),
                ('responsavel_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Atual')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_patrimonio', to='patrimonio.localizacaopatrimonio', verbose_name='Localização Atual')),
            ],
            options={
                'verbose_name': 'Item de Patrimônio',
                'verbose_name_plural': 'Itens de Patrimônio',
                'ordering': ['nome', 'codigo_patrimonial'],
            },
        ),
    ]
