# Generated by Django 5.2.3 on 2025-06-27 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itempatrimonio',
            name='data_baixa',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Baixa'),
        ),
        migrations.AddField(
            model_name='itempatrimonio',
            name='motivo_baixa',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Baixa'),
        ),
        migrations.AddField(
            model_name='itempatrimonio',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('BAIXADO', 'Baixado'), ('TRANSFERIDO', 'Transferido')], default='ATIVO', max_length=20, verbose_name='Status do Item'),
        ),
        migrations.AlterField(
            model_name='itempatrimonio',
            name='responsavel_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_patrimonio_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Atual'),
        ),
        migrations.CreateModel(
            name='MovimentacaoPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('AQUISICAO', 'Aquisição'), ('TRANSFERENCIA', 'Transferência'), ('BAIXA', 'Baixa'), ('MANUTENCAO', 'Manutenção'), ('INVENTARIO', 'Inventário')], max_length=50, verbose_name='Tipo de Movimentação')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('item_patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='patrimonio.itempatrimonio')),
                ('localizacao_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_patrimonio_origem', to='patrimonio.localizacaopatrimonio', verbose_name='Localização Anterior')),
                ('localizacao_nova', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_patrimonio_destino', to='patrimonio.localizacaopatrimonio', verbose_name='Nova Localização')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_patrimonio_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Realizado Por')),
                ('responsavel_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_patrimonio_resp_anterior', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Anterior')),
                ('responsavel_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_patrimonio_resp_novo', to=settings.AUTH_USER_MODEL, verbose_name='Novo Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de Patrimônio',
                'verbose_name_plural': 'Movimentações de Patrimônio',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
