# Generated by Django 5.2.3 on 2025-06-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_itempatrimonio_data_baixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaopatrimonio',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da Movimentação'),
        ),
    ]
