# Generated by Django 5.2.3 on 2025-06-27 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0003_movimentacaopatrimonio_observacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaopatrimonio',
            name='item_patrimonio',
        ),
        migrations.RemoveField(
            model_name='movimentacaopatrimonio',
            name='localizacao_anterior',
        ),
        migrations.RemoveField(
            model_name='movimentacaopatrimonio',
            name='localizacao_nova',
        ),
        migrations.RemoveField(
            model_name='movimentacaopatrimonio',
            name='realizado_por',
        ),
        migrations.RemoveField(
            model_name='movimentacaopatrimonio',
            name='responsavel_anterior',
        ),
        migrations.RemoveField(
            model_name='movimentacaopatrimonio',
            name='responsavel_novo',
        ),
        migrations.AddField(
            model_name='movimentacaopatrimonio',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='patrimonio.itempatrimonio', verbose_name='Item de Patrimônio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacaopatrimonio',
            name='localizacao_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='patrimonio.localizacaopatrimonio', verbose_name='Localização de Destino'),
        ),
        migrations.AddField(
            model_name='movimentacaopatrimonio',
            name='localizacao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='patrimonio.localizacaopatrimonio', verbose_name='Localização de Origem'),
        ),
        migrations.AddField(
            model_name='movimentacaopatrimonio',
            name='responsavel_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_resp_destino', to=settings.AUTH_USER_MODEL, verbose_name='Responsável de Destino'),
        ),
        migrations.AddField(
            model_name='movimentacaopatrimonio',
            name='responsavel_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_resp_origem', to=settings.AUTH_USER_MODEL, verbose_name='Responsável de Origem'),
        ),
        migrations.AddField(
            model_name='movimentacaopatrimonio',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Registro'),
        ),
        migrations.AlterField(
            model_name='movimentacaopatrimonio',
            name='data_movimentacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Movimentação'),
        ),
    ]
