# Generated by Django 5.2.3 on 2025-06-27 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_remove_movimentacaopatrimonio_item_patrimonio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itempatrimonio',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por'),
        ),
    ]
