# Generated by Django 5.2.3 on 2025-06-27 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0005_itempatrimonio_usuario_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColetaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora da Coleta')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações da Coleta')),
                ('item_patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas_inventario', to='patrimonio.itempatrimonio', verbose_name='Item de Patrimônio')),
                ('localizacao_coleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonio.localizacaopatrimonio', verbose_name='Localização da Coleta')),
                ('usuario_coleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Coletou')),
            ],
            options={
                'verbose_name': 'Coleta de Inventário',
                'verbose_name_plural': 'Coletas de Inventário',
                'ordering': ['-data_coleta'],
            },
        ),
    ]
