# Generated by Django 5.2.3 on 2025-07-01 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_cep_cliente_cidade_cliente_data_nascimento_and_more'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_a_receber_cliente', to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
