# Generated by Django 5.2.3 on 2025-07-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_contareceber_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
