# pat/meu_projeto_admin/settings.py

"""
Django settings for meu_projeto_admin project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Importar 'os' para os.path.join

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+87td)_3hi3@7sk@p%1%-udgo6s+i_%p22_ouu(w%w&u6*+dp2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'usuarios',  # Seu novo app 'usuarios' adicionado aqui <-- Linha 44 ajustada aqui
    'estoque',
    'patrimonio',
    'fornecedores',
    'clientes', 
    'epi',
    'crispy_forms',           # <--- Certifique-se de que estas linhas estão aqui
    'crispy_bootstrap5',      # <--- Certifique-se de que estas linhas estão aqui
    'financeiro',
    'django_filters',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meu_projeto_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Caminho para a pasta de templates globais do projeto
        'APP_DIRS': True, # Permite que o Django procure templates dentro das pastas 'templates' de cada app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Adicionado para auxiliar no debug
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meu_projeto_admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# --- Configurações de Localização (L10N) para o Brasil ---
USE_L10N = True # Garante que formatos localizados serão usados
DECIMAL_SEPARATOR = ',' # Usa vírgula como separador decimal
USE_THOUSAND_SEPARATORS = True # Habilita separadores de milhares
THOUSAND_SEPARATOR = '.' # Usa ponto como separador de milhares
NUMBER_GROUPING = (3, 0) # Agrupamento de números: (3, 0) para 1.000.000 (grupos de 3 dígitos)
# --------------------------------------------------------


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Adicione estas linhas para configurar o STATICFILES_DIRS e STATIC_ROOT
# STATICFILES_DIRS: Lista de pastas onde o Django irá procurar arquivos estáticos
# em tempo de desenvolvimento (além das pastas 'static' dentro de cada app).
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"), # Usando os.path.join para compatibilidade
]
# STATIC_ROOT: Pasta onde 'python manage.py collectstatic' vai copiar todos os arquivos estáticos
# de todos os apps e STATICFILES_DIRS, para ser servido em produção.
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# --- Configurações para arquivos de Mídia (uploads de usuários, como PDFs e assinaturas) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Onde os arquivos de mídia serão salvos fisicamente
# -----------------------------------------------------------------------------------------


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Configurações de Autenticação e Redirecionamento ---
# URL para redirecionar após um login bem-sucedido
LOGIN_REDIRECT_URL = '/'
# URL da página de login
LOGIN_URL = '/accounts/login/'
# URL para redirecionar após um logout bem-sucedido
LOGOUT_REDIRECT_URL = '/accounts/login/'
# --------------------------------------------------------

# --- Configurações para Django Crispy Forms ---
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
# ---------------------------------------------